/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ObjectivesIndexRouteImport } from './routes/objectives.index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ReviewCaseIdRouteImport } from './routes/review.$caseId'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ObjectivesSlugRouteImport } from './routes/objectives/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as ObjectivesSlugIndexRouteImport } from './routes/objectives/$slug/index'
import { Route as GuidesSlugIndexRouteImport } from './routes/guides/$slug/index'
import { Route as GuidesSlugWalkthroughRouteImport } from './routes/guides/$slug/walkthrough'
import { Route as GuidesSlugVariantSlugIndexRouteImport } from './routes/guides/$slug/$variantSlug/index'
import { Route as ObjectivesSlugRevisionsRevisionIdRouteImport } from './routes/objectives/$slug/revisions.$revisionId'
import { Route as GuidesSlugVariantSlugEditRouteImport } from './routes/guides/$slug/$variantSlug/edit'
import { Route as GuidesSlugVariantSlugRevisionsRevisionIdRouteImport } from './routes/guides/$slug/$variantSlug/revisions.$revisionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ObjectivesIndexRoute = ObjectivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObjectivesRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ReviewCaseIdRoute = ReviewCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ReviewRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRoute,
} as any)
const ObjectivesSlugRoute = ObjectivesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ObjectivesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const ObjectivesSlugIndexRoute = ObjectivesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObjectivesSlugRoute,
} as any)
const GuidesSlugIndexRoute = GuidesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesSlugRoute,
} as any)
const GuidesSlugWalkthroughRoute = GuidesSlugWalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => GuidesSlugRoute,
} as any)
const GuidesSlugVariantSlugIndexRoute =
  GuidesSlugVariantSlugIndexRouteImport.update({
    id: '/$variantSlug/',
    path: '/$variantSlug/',
    getParentRoute: () => GuidesSlugRoute,
  } as any)
const ObjectivesSlugRevisionsRevisionIdRoute =
  ObjectivesSlugRevisionsRevisionIdRouteImport.update({
    id: '/revisions/$revisionId',
    path: '/revisions/$revisionId',
    getParentRoute: () => ObjectivesSlugRoute,
  } as any)
const GuidesSlugVariantSlugEditRoute =
  GuidesSlugVariantSlugEditRouteImport.update({
    id: '/$variantSlug/edit',
    path: '/$variantSlug/edit',
    getParentRoute: () => GuidesSlugRoute,
  } as any)
const GuidesSlugVariantSlugRevisionsRevisionIdRoute =
  GuidesSlugVariantSlugRevisionsRevisionIdRouteImport.update({
    id: '/$variantSlug/revisions/$revisionId',
    path: '/$variantSlug/revisions/$revisionId',
    getParentRoute: () => GuidesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/todos': typeof TodosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/guides/$slug': typeof GuidesSlugRouteWithChildren
  '/objectives/$slug': typeof ObjectivesSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
  '/objectives/$slug/': typeof ObjectivesSlugIndexRoute
  '/guides/$slug/$variantSlug/edit': typeof GuidesSlugVariantSlugEditRoute
  '/objectives/$slug/revisions/$revisionId': typeof ObjectivesSlugRevisionsRevisionIdRoute
  '/guides/$slug/$variantSlug/': typeof GuidesSlugVariantSlugIndexRoute
  '/guides/$slug/$variantSlug/revisions/$revisionId': typeof GuidesSlugVariantSlugRevisionsRevisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/todos': typeof TodosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/objectives': typeof ObjectivesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug': typeof GuidesSlugIndexRoute
  '/objectives/$slug': typeof ObjectivesSlugIndexRoute
  '/guides/$slug/$variantSlug/edit': typeof GuidesSlugVariantSlugEditRoute
  '/objectives/$slug/revisions/$revisionId': typeof ObjectivesSlugRevisionsRevisionIdRoute
  '/guides/$slug/$variantSlug': typeof GuidesSlugVariantSlugIndexRoute
  '/guides/$slug/$variantSlug/revisions/$revisionId': typeof GuidesSlugVariantSlugRevisionsRevisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/todos': typeof TodosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/guides/$slug': typeof GuidesSlugRouteWithChildren
  '/objectives/$slug': typeof ObjectivesSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
  '/objectives/$slug/': typeof ObjectivesSlugIndexRoute
  '/guides/$slug/$variantSlug/edit': typeof GuidesSlugVariantSlugEditRoute
  '/objectives/$slug/revisions/$revisionId': typeof ObjectivesSlugRevisionsRevisionIdRoute
  '/guides/$slug/$variantSlug/': typeof GuidesSlugVariantSlugIndexRoute
  '/guides/$slug/$variantSlug/revisions/$revisionId': typeof GuidesSlugVariantSlugRevisionsRevisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contribute'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/settings'
    | '/subjects'
    | '/todos'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/members'
    | '/dashboard/roles'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/profile/$username'
    | '/review/$caseId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/profile'
    | '/subjects/$slug'
    | '/dashboard/'
    | '/guides/'
    | '/objectives/'
    | '/review/'
    | '/settings/'
    | '/subjects/'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug/'
    | '/objectives/$slug/'
    | '/guides/$slug/$variantSlug/edit'
    | '/objectives/$slug/revisions/$revisionId'
    | '/guides/$slug/$variantSlug/'
    | '/guides/$slug/$variantSlug/revisions/$revisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contribute'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/todos'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/members'
    | '/dashboard/roles'
    | '/profile/$username'
    | '/review/$caseId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/profile'
    | '/subjects/$slug'
    | '/dashboard'
    | '/guides'
    | '/objectives'
    | '/review'
    | '/settings'
    | '/subjects'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/guides/$slug/$variantSlug/edit'
    | '/objectives/$slug/revisions/$revisionId'
    | '/guides/$slug/$variantSlug'
    | '/guides/$slug/$variantSlug/revisions/$revisionId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/contribute'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/settings'
    | '/subjects'
    | '/todos'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/members'
    | '/dashboard/roles'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/profile/$username'
    | '/review/$caseId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/profile'
    | '/subjects/$slug'
    | '/dashboard/'
    | '/guides/'
    | '/objectives/'
    | '/review/'
    | '/settings/'
    | '/subjects/'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug/'
    | '/objectives/$slug/'
    | '/guides/$slug/$variantSlug/edit'
    | '/objectives/$slug/revisions/$revisionId'
    | '/guides/$slug/$variantSlug/'
    | '/guides/$slug/$variantSlug/revisions/$revisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ContributeRoute: typeof ContributeRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ObjectivesRoute: typeof ObjectivesRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SubjectsRoute: typeof SubjectsRouteWithChildren
  TodosRoute: typeof TodosRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  GuidesSlugRoute: typeof GuidesSlugRouteWithChildren
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/objectives/': {
      id: '/objectives/'
      path: '/'
      fullPath: '/objectives/'
      preLoaderRoute: typeof ObjectivesIndexRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/review/$caseId': {
      id: '/review/$caseId'
      path: '/$caseId'
      fullPath: '/review/$caseId'
      preLoaderRoute: typeof ReviewCaseIdRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/objectives/$slug': {
      id: '/objectives/$slug'
      path: '/$slug'
      fullPath: '/objectives/$slug'
      preLoaderRoute: typeof ObjectivesSlugRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/objectives/$slug/': {
      id: '/objectives/$slug/'
      path: '/'
      fullPath: '/objectives/$slug/'
      preLoaderRoute: typeof ObjectivesSlugIndexRouteImport
      parentRoute: typeof ObjectivesSlugRoute
    }
    '/guides/$slug/': {
      id: '/guides/$slug/'
      path: '/'
      fullPath: '/guides/$slug/'
      preLoaderRoute: typeof GuidesSlugIndexRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
    '/guides/$slug/walkthrough': {
      id: '/guides/$slug/walkthrough'
      path: '/walkthrough'
      fullPath: '/guides/$slug/walkthrough'
      preLoaderRoute: typeof GuidesSlugWalkthroughRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
    '/guides/$slug/$variantSlug/': {
      id: '/guides/$slug/$variantSlug/'
      path: '/$variantSlug'
      fullPath: '/guides/$slug/$variantSlug/'
      preLoaderRoute: typeof GuidesSlugVariantSlugIndexRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
    '/objectives/$slug/revisions/$revisionId': {
      id: '/objectives/$slug/revisions/$revisionId'
      path: '/revisions/$revisionId'
      fullPath: '/objectives/$slug/revisions/$revisionId'
      preLoaderRoute: typeof ObjectivesSlugRevisionsRevisionIdRouteImport
      parentRoute: typeof ObjectivesSlugRoute
    }
    '/guides/$slug/$variantSlug/edit': {
      id: '/guides/$slug/$variantSlug/edit'
      path: '/$variantSlug/edit'
      fullPath: '/guides/$slug/$variantSlug/edit'
      preLoaderRoute: typeof GuidesSlugVariantSlugEditRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
    '/guides/$slug/$variantSlug/revisions/$revisionId': {
      id: '/guides/$slug/$variantSlug/revisions/$revisionId'
      path: '/$variantSlug/revisions/$revisionId'
      fullPath: '/guides/$slug/$variantSlug/revisions/$revisionId'
      preLoaderRoute: typeof GuidesSlugVariantSlugRevisionsRevisionIdRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ObjectivesSlugRouteChildren {
  ObjectivesSlugIndexRoute: typeof ObjectivesSlugIndexRoute
  ObjectivesSlugRevisionsRevisionIdRoute: typeof ObjectivesSlugRevisionsRevisionIdRoute
}

const ObjectivesSlugRouteChildren: ObjectivesSlugRouteChildren = {
  ObjectivesSlugIndexRoute: ObjectivesSlugIndexRoute,
  ObjectivesSlugRevisionsRevisionIdRoute:
    ObjectivesSlugRevisionsRevisionIdRoute,
}

const ObjectivesSlugRouteWithChildren = ObjectivesSlugRoute._addFileChildren(
  ObjectivesSlugRouteChildren,
)

interface ObjectivesRouteChildren {
  ObjectivesSlugRoute: typeof ObjectivesSlugRouteWithChildren
  ObjectivesIndexRoute: typeof ObjectivesIndexRoute
}

const ObjectivesRouteChildren: ObjectivesRouteChildren = {
  ObjectivesSlugRoute: ObjectivesSlugRouteWithChildren,
  ObjectivesIndexRoute: ObjectivesIndexRoute,
}

const ObjectivesRouteWithChildren = ObjectivesRoute._addFileChildren(
  ObjectivesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUsernameRoute: ProfileUsernameRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ReviewRouteChildren {
  ReviewCaseIdRoute: typeof ReviewCaseIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewCaseIdRoute: ReviewCaseIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

interface GuidesSlugRouteChildren {
  GuidesSlugWalkthroughRoute: typeof GuidesSlugWalkthroughRoute
  GuidesSlugIndexRoute: typeof GuidesSlugIndexRoute
  GuidesSlugVariantSlugEditRoute: typeof GuidesSlugVariantSlugEditRoute
  GuidesSlugVariantSlugIndexRoute: typeof GuidesSlugVariantSlugIndexRoute
  GuidesSlugVariantSlugRevisionsRevisionIdRoute: typeof GuidesSlugVariantSlugRevisionsRevisionIdRoute
}

const GuidesSlugRouteChildren: GuidesSlugRouteChildren = {
  GuidesSlugWalkthroughRoute: GuidesSlugWalkthroughRoute,
  GuidesSlugIndexRoute: GuidesSlugIndexRoute,
  GuidesSlugVariantSlugEditRoute: GuidesSlugVariantSlugEditRoute,
  GuidesSlugVariantSlugIndexRoute: GuidesSlugVariantSlugIndexRoute,
  GuidesSlugVariantSlugRevisionsRevisionIdRoute:
    GuidesSlugVariantSlugRevisionsRevisionIdRoute,
}

const GuidesSlugRouteWithChildren = GuidesSlugRoute._addFileChildren(
  GuidesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ContributeRoute: ContributeRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ObjectivesRoute: ObjectivesRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SubjectsRoute: SubjectsRouteWithChildren,
  TodosRoute: TodosRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  GuidesSlugRoute: GuidesSlugRouteWithChildren,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
